### ISSUE TITLE
Can't start postfix after reboot.

### ISSUE THREAD

**Issue by malsony** [drewlander/mailonacircle#5]
Got an error message:
```
postfix/submission/smtpd[xxxxx]: warning: connect to Milter service unix:/var/run/clamav-milter/clamav-milter.socket: Permission denied
```
after every reboot, and can't send any mail out.

And I enter the command in last step according to the "cookbook":
```
setfacl -m u:postfix:rx /var/run/clamav-milter
```
and everything is fine.

Maybe add a line in `/etc/rc.d/rc.local`? And then make sure that `/etc/rc.d/rc.local` is executable so that the admin does not have to enter that manually.

Any idea?

**Comment by drewlander** [comment]
wow this is what I get for not touching this project in a while. I would love to setup some CI. if that fixes it we can, but you shouldnt have to do that every time. that can be added in the recipe. setfacl should persist. The other alternative is to use the port for clamav-milter instead of the socket file in postfix's main.cf

**Comment by drewlander** [comment]
there will be a change incoming. just had to make a new policy module for selinux

**Comment by drewlander** [comment]
Closing this issue. did a fresh install, rebooted multiple times, works well.
